/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.PessoaDAO;
import DAO.VacinaDAO;
import DAO.VacinacaoDAO;
import JTableModels.TableModel;
import Models.Pessoa;
import Models.Usuario;
import Models.Vacina;
import Models.Vacinacao;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author caioe
 */
public class TelaFilaVacinacao extends javax.swing.JFrame {
    private Usuario usuario;
     private List<Pessoa> fila = new ArrayList<>();;
    /**
     * Creates new form TelaFilaVacinacao
     */
    public TelaFilaVacinacao() {
        initComponents();
        buscarVacinas();
        buscarFila();
        atualizaFila();
    }
    public TelaFilaVacinacao(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        buscarVacinas();
        buscarFila();
        atualizaFila();
    }
    private void buscarVacinas(){
        try{
            VacinaDAO dao = new VacinaDAO();
            Vacina[] vacinas = dao.obtemVacinas();
            vacinasComboBox.setModel(new DefaultComboBoxModel<>(vacinas));
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problema");
            
        }
    }
    
    private void buscarFila() {
        try{
            //filaTable.setModel(null);
            PessoaDAO pessoaDao = new PessoaDAO();
            
            List<Pessoa> pessoas = Arrays.asList(pessoaDao.obtemFila());
            //Collections.sort(pacientes);
            //Pessoa[] pessoas = pessoaDao.obtemPacientes();

            List<Pessoa> prioridade1 = new ArrayList<>();
            List<Pessoa> prioridade2 = new ArrayList<>();
            List<Pessoa> prioridade3 = new ArrayList<>();
            
           for(int i = 0; i < pessoas.size();i++){
               
               if(pessoas.get(i).getIdade()>= 70){
                   
                   prioridade1.add(pessoas.get(i));
                   
               }else if(pessoas.get(i).isTrabalhaComSaude()){
                   
                   prioridade2.add(pessoas.get(i));
                   
               }else {
                   prioridade3.add(pessoas.get(i));
               }
           }
           prioridade1.addAll(prioridade2);
           prioridade1.addAll(prioridade3);
           fila.addAll(prioridade1);
                        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problema aqui");
        }
        
    }
    
    private void atualizaFila(){
        filaTable.setModel(new TableModel(fila));
        
        nomeLabel.setText(fila.get(0).getNome());
        idadeLabel.setText(String.valueOf(fila.get(0).getIdade()));
        rgLabel.setText(fila.get(0).getRg());     
        trabalhaSaudeCheckBox.setSelected(fila.get(0).isTrabalhaComSaude());
        trabalhaSaudeCheckBox.enableInputMethods(false);
        if(fila.get(0).getIdade()>= 70){ prioridadeLabel.setText("1");
        }else if(fila.get(0).isTrabalhaComSaude()){ prioridadeLabel.setText("2");
        }else { prioridadeLabel.setText("3");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registraVacinacaoButton = new javax.swing.JButton();
        vacinasComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        idadeLabel = new javax.swing.JLabel();
        prioridadeLabel = new javax.swing.JLabel();
        trabalhaSaudeCheckBox = new javax.swing.JCheckBox();
        pularButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filaTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 600));
        setPreferredSize(new java.awt.Dimension(680, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        registraVacinacaoButton.setText("Registrar Aplicacão");
        registraVacinacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraVacinacaoButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nivel Prioridade:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Idade:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("RG:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Selecionar Vacina:");

        nomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomeLabel.setText("fulano");

        rgLabel.setForeground(new java.awt.Color(0, 0, 0));
        rgLabel.setText("0000000");

        idadeLabel.setForeground(new java.awt.Color(0, 0, 0));
        idadeLabel.setText("12");

        prioridadeLabel.setForeground(new java.awt.Color(0, 0, 0));
        prioridadeLabel.setText("2");

        trabalhaSaudeCheckBox.setText("Trabalha na Saude");
        trabalhaSaudeCheckBox.setEnabled(false);

        pularButton.setText("Pular");
        pularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioridadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(trabalhaSaudeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vacinasComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registraVacinacaoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pularButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nomeLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pularButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(idadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rgLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registraVacinacaoButton)
                            .addComponent(jLabel2)
                            .addComponent(prioridadeLabel)
                            .addComponent(trabalhaSaudeCheckBox)))
                    .addComponent(vacinasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(41, 124, 609, 136);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vez de:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 96, 56, 16);

        filaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Idade", "RG:", "Trabalha Saude"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(filaTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(41, 284, 577, 189);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Proximos:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(41, 266, 77, 16);

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(41, 491, 74, 24);

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(552, 491, 57, 24);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fila de Vacinação");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(86, 22, 434, 68);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\caioe\\OneDrive\\Área de Trabalho\\TelasProjeto\\Tela6FilaVacinacao.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 670, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(usuario.getTipo().equals("adm")){
            TelaAdmin a = new TelaAdmin(usuario);
            a.setVisible(true);
            a.setLocationRelativeTo(null);
        } else {
            TelaAtendente a = new TelaAtendente(usuario);
            a.setVisible(true);
            a.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void registraVacinacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraVacinacaoButtonActionPerformed
        // TODO add your handling code here:
        try{
        int escolha = JOptionPane.showConfirmDialog(this, "Confirma a aplicação desta vacinação? ");     
        if (escolha == JOptionPane.YES_OPTION){
            
        Date data = new Date();
        VacinacaoDAO vacinacaoDao = new VacinacaoDAO();
        VacinaDAO vacinaDao = new VacinaDAO();
        
        Vacina vacina = (Vacina)vacinasComboBox.getSelectedItem();
        Vacinacao vacinacao = new Vacinacao(data,fila.get(0).getRg(),vacina.getCodigo(),this.usuario.getLogin());
        vacinacaoDao.cadastraVacinacao(vacinacao);
        vacinaDao.DebitaVacina(vacina);
        
        JOptionPane.showMessageDialog(this, "Vacinação aplicada com Sucesso !");
        this.fila.remove(0);
        atualizaFila();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problema aqui");
            e.printStackTrace();
        }
    }//GEN-LAST:event_registraVacinacaoButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void pularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pularButtonActionPerformed
        // TODO add your handling code here:
        this.fila.remove(0);
        atualizaFila();
    }//GEN-LAST:event_pularButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFilaVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFilaVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFilaVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFilaVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFilaVacinacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable filaTable;
    private javax.swing.JLabel idadeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel prioridadeLabel;
    private javax.swing.JButton pularButton;
    private javax.swing.JButton registraVacinacaoButton;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JButton sairButton;
    private javax.swing.JCheckBox trabalhaSaudeCheckBox;
    private javax.swing.JComboBox vacinasComboBox;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
