package Telas;

import DAO.UsuarioDAO;
import Models.Usuario;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change thissda template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author andre
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTextField = new javax.swing.JFormattedTextField();
        textLogin = new javax.swing.JLabel();
        textSenha = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        senhaTextField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(520, 330));
        getContentPane().setLayout(null);

        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField);
        loginTextField.setBounds(170, 120, 136, 30);

        textLogin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        textLogin.setText("Usuário:");
        getContentPane().add(textLogin);
        textLogin.setBounds(220, 100, 51, 16);

        textSenha.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textSenha.setForeground(new java.awt.Color(255, 255, 255));
        textSenha.setText("Senha:");
        getContentPane().add(textSenha);
        textSenha.setBounds(220, 160, 43, 16);

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(170, 220, 65, 24);

        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(240, 220, 70, 24);

        senhaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaTextField);
        senhaTextField.setBounds(170, 180, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\caioe\\OneDrive\\Área de Trabalho\\Projeto\\src\\main\\java\\ImagensProjeto\\TelaLogin.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1, -4, 500, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed

        dispose();
        System.exit(0);
// Comando para fechar o programa, ao clicar em sair:
    }//GEN-LAST:event_sairButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
//pegar os valores dos inputs
        String login = loginTextField.getText();
        String senha = String.valueOf(senhaTextField.getPassword());
        Usuario usuario = new Usuario(login, senha);

        UsuarioDAO usuarioDAO = new UsuarioDAO();
        Usuario usuarioAchado = usuarioDAO.buscaUsuario(usuario);
        
        System.out.println(usuarioAchado.getNome());
        
        
        if (usuarioAchado != null) {
            JOptionPane.showMessageDialog(this, "Bem vindo " + usuarioAchado.getNome() + " !");
            this.dispose();

            if (usuarioAchado.getTipo().equals("adm")) {
                TelaAdmin adm = new TelaAdmin(usuarioAchado);
                adm.setVisible(true);
                setLocationRelativeTo(null);
            } else {
                TelaAtendente a = new TelaAtendente(usuarioAchado);
                a.setVisible(true);
                a.setLocationRelativeTo(null);
            }
            //new DashboardTela().setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Usuario ou senha invalidas ",
                    usuario.getNome() + " !", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void senhaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JFormattedTextField loginTextField;
    private javax.swing.JButton sairButton;
    private javax.swing.JPasswordField senhaTextField;
    private javax.swing.JLabel textLogin;
    private javax.swing.JLabel textSenha;
    // End of variables declaration//GEN-END:variables
}
