/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.PessoaDAO;
import Models.Pessoa;
import Models.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaCadastroPaciente extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form TelaVacinacao
     */
    public TelaCadastroPaciente() {
        initComponents();
    }
    public TelaCadastroPaciente(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        textNomeTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nomeTextField = new javax.swing.JTextPane();
        textIdade = new javax.swing.JLabel();
        textEndereco = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enderecoTextField = new javax.swing.JTextPane();
        cadastrarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idadeSpinner = new javax.swing.JSpinner();
        rgTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        trabalhaSaudeCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setMinimumSize(new java.awt.Dimension(445, 585));
        getContentPane().setLayout(null);

        textNomeTitulo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textNomeTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textNomeTitulo.setText("Nome:");
        getContentPane().add(textNomeTitulo);
        textNomeTitulo.setBounds(20, 150, 50, 20);

        jScrollPane1.setViewportView(nomeTextField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 140, 300, 30);

        textIdade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textIdade.setForeground(new java.awt.Color(255, 255, 255));
        textIdade.setText("Idade:");
        getContentPane().add(textIdade);
        textIdade.setBounds(250, 206, 50, 20);

        textEndereco.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textEndereco.setForeground(new java.awt.Color(255, 255, 255));
        textEndereco.setText("Endereço:");
        getContentPane().add(textEndereco);
        textEndereco.setBounds(20, 250, 90, 16);

        jScrollPane2.setViewportView(enderecoTextField);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(100, 240, 270, 30);

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton);
        cadastrarButton.setBounds(110, 340, 190, 24);

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(110, 380, 190, 24);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 550);
        getContentPane().add(idadeSpinner);
        idadeSpinner.setBounds(310, 200, 60, 26);
        getContentPane().add(rgTextField);
        rgTextField.setBounds(50, 200, 150, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 21, 16);

        trabalhaSaudeCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        trabalhaSaudeCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        trabalhaSaudeCheckBox.setText("É um Profissional da area da saúde");
        trabalhaSaudeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabalhaSaudeCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(trabalhaSaudeCheckBox);
        trabalhaSaudeCheckBox.setBounds(150, 290, 220, 24);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\caioe\\OneDrive\\Área de Trabalho\\Projeto\\src\\main\\java\\ImagensProjeto\\TelaVacina.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 430, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        String nome = nomeTextField.getText();
        String rg = rgTextField.getText();
        int idade = Integer.parseInt(idadeSpinner.getValue().toString());
        String endereco = enderecoTextField.getText();
        boolean trabalhaSaude = trabalhaSaudeCheckBox.isSelected();
        
        if(nome.length() == 0 || rg.length() == 0 || idade <= 0 || endereco.length() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }
        try{
            int escolha = JOptionPane.showConfirmDialog(this, "Confirma o cadastro desta Pessoa? ");
            
            if (escolha == JOptionPane.YES_OPTION){
                
                Pessoa paciente = new Pessoa(rg, nome, idade, endereco, trabalhaSaude);
                PessoaDAO pessoaDAO = new PessoaDAO();
                pessoaDAO.cadastraPaciente(paciente);
                JOptionPane.showMessageDialog(this, "Paciente Cadastrado com Sucesso !");
                
                nomeTextField.setText("");
                rgTextField.setText("");
                idadeSpinner.setValue(0);
                enderecoTextField.setText("");
                trabalhaSaudeCheckBox.setSelected(false);
                
            }
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Falha Tecnica, tente mais tarde!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
        TelaGerenciaPaciente n = new TelaGerenciaPaciente(usuario);
        n.setVisible(true);
        n.setLocationRelativeTo(null);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void trabalhaSaudeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabalhaSaudeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trabalhaSaudeCheckBoxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextPane enderecoTextField;
    private javax.swing.JSpinner idadeSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane nomeTextField;
    private javax.swing.JTextField rgTextField;
    private javax.swing.JLabel textEndereco;
    private javax.swing.JLabel textIdade;
    private javax.swing.JLabel textNomeTitulo;
    private javax.swing.JCheckBox trabalhaSaudeCheckBox;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
